### ISSUE TITLE
子设备显示未激活

### ISSUE THREAD

**Issue by iwetuan** [ctlove0523/huaweicloud-iot-device-sdk-go#2]
你好，执行网关批量上报子设备属性的操作，平台上可以看到子设备上报的数据，但是子设备显示未激活，
如何解决呢？
![image](https://user-images.githubusercontent.com/10174253/109610220-6a49c700-7b67-11eb-891f-f2f178b08ba2.png)

**Comment by ctlove0523** [comment]
子设备的状态需要网关上报到IoT平台，可以调用`UpdateSubDeviceState`方法上报子设备状态

**Comment by iwetuan** [comment]
谢谢帮助，调用UpdateSubDeviceState，现在子设备已经可以显示在线了
